export const SET_SORT_FIELD = "SET_SORT_FIELD";
export const SET_ORDER_BY_SORT = "SET_ORDER_BY_SORT";
export const SET_FILTERED = "SET_FILTERED";
export const SET_START_DATE = "SET_START_DATE";
export const SET_END_DATE = "SET_END_DATE";
export const APPOINTMENTS_SORT = "APPOINTMENTS_SORT";
export const APPOINTMENTS_FILTER = "APPOINTMENTS_FILTER";

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const ADD_APPOINTMENTS = "ADD_APPOINTMENTS";
export const EDIT_APPOINTMENTS = "EDIT_APPOINTMENTS";
export const DELETE_APPOINTMENTS = "DELETE_APPOINTMENTS";
